spring:
    datasource:
        druid:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/shopdb?useUnicode=true&amp;characterEncoding=UTF-8
            username: root
            password:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 30000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: select '1' from hiolabsdb
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall
            aop-patterns: com.teststantd.demo.servie.*


######### 分页插件 ##########
pagehelper:
    helper-dialect: mysql
    params-count: countSql
    reasonable: false
    support-methods-arguments: true